title = "auto_aim"
version = 1.0

[camera]
version = "MV" # MV: MindVision; HK: Hikvision
focal = [1037.06391, 1036.44396]
center = [306.61321, 228.42354]
dist = [-0.108574, 0.260086, 0.000301, 0.001182, 0.000000]

[mindvision]
gamma = 110          # 伽马值
contrast = 100       # 对比度
saturation = 100     # 饱和度
auto_exposure = true # 是否开启自动曝光
exposure_time = 12   # 曝光时间 (ms)

[hikvision]
auto_whitebalance = true # 是否开启自动白平衡
auto_exposure = true    # 是否开启自动曝光
exposure_time = 5000       # 曝光时间

[aim_armor]
model_path = "assets/model/best.onnx"

# [aim_armor.light]
# aspect_ratio = [1, 15]
# area = [120, inf]

[aim_armor.light]
aspect_ratio = [-inf, inf]
area = [40, inf]

[aim_armor.armor]
aspect_ratio = [-inf, inf]   # FIXME
edge_angle = [40, 150]
original_angle = [-inf, inf]

[serial]
port = ["/dev/ttyUSB*", "/dev/ttyCH341USB*", "/dev/ttyACM*"]
baud_rate = 115200

[test]
test_video = "./1.avi"

# TODO: 重排与拆分
