title = "auto_aim"
version = 1.0

[camera]
version = "MV"  # MV：MindVision；HK：Hikvision

[aim_aromr]
model_path = "./assets/model/best-8.onnx"
classes = ["1", "2", "3", "4", "base", "qsz", "sb", "null"]