title = "auto_aim"
version = 1.0

[camera]
version = "HK" # MV: MindVision; HK: Hikvision
focal = [1050.176611784291254, 1050.3160947995561]
center = [301.8079077070227, 225.2905375296807]
dist = [
  -0.0893641782114391,
  -0.5153697191214612,
  -0.0008147925966741238,
  -0.0000383217287733705,
  8.961592240034004,
]

[mindvision]
gamma = 110           # 伽马值
contrast = 100        # 对比度
saturation = 100      # 饱和度
auto_exposure = false # 是否开启自动曝光
exposure_time = 30    # 曝光时间 (ms)

[hikvision]
brightness = 100         # 亮度
auto_whitebalance = true # 是否开启自动白平衡
auto_exposure = false    # 是否开启自动曝光
exposure_time = 10       # 曝光时间 (ms)

[aim_aromr]
model_path = "assets/model/best-8.onnx"
classes = ["1", "2", "3", "4", "base", "qsz", "sb", "null"]
# TODO: 使用单字符区分

[aim_aromr.light]
aspect_radio = [2.2, inf]
area = [60, inf]

[aim_aromr.armor]
aspect_radio = [-inf, inf]   # FIXME
edge_angle = [75, 105]
original_angle = [-inf, inf]

[serial]
port = "/dev/ttyUSB0"
in_baud_rate = 115200
out_baud_rate = 115200

[test]
test_video = "./1.avi"

# TODO: 重排与拆分
