title = "auto_aim"
version = 1.0

[camera]
version = "MV" # MV: MindVision; HK: Hikvision
# focal = [1079.252773, 1087.934656]
focal = [1080, 1080]
center = [320.000000, 240.000000]
dist = [
  -0.100173,
  0.216010,
  -0.027498,
  -0.002229,
  0.000000
]

[mindvision]
gamma = 110          # 伽马值
contrast = 100       # 对比度
saturation = 100     # 饱和度
auto_exposure = true # 是否开启自动曝光
exposure_time = 12   # 曝光时间 (ms)

[hikvision]
auto_whitebalance = true # 是否开启自动白平衡
auto_exposure = false    # 是否开启自动曝光
exposure_time = 12       # 曝光时间 (ms)

[aim_armor]
model_path = "assets/model/best-8.onnx"

# [aim_armor.light]
# aspect_ratio = [1, 15]
# area = [120, inf]

[aim_armor.light]
aspect_ratio = [-inf, inf]
area = [120, inf]

[aim_armor.armor]
aspect_ratio = [-inf, inf]   # FIXME
edge_angle = [70, 108]
original_angle = [-inf, inf]

[serial]
port = ["/dev/ttyUSB*", "/dev/ttyCH341USB*"]
baud_rate = 2000000

[test]
test_video = "./1.avi"

# TODO: 重排与拆分
