title = "auto_aim"
version = 1.0

[camera]
version = "MV"  # MV：MindVision；HK：Hikvision

[aim_aromr]
model_path = "./assets/model/best-8.onnx"
classes = ["1", "2", "3", "4", "base", "qsz", "sb", "null"]

[serial]
device_name= "/dev/tty0"
baud_rate = 115200

[test]
test_video = "./1.avi"